
// Generated by Cadence Encounter(R) RTL Compiler v12.10-s012_1

// Verification Directory fv/counter 

module counter(c, rst, clk, en);
  input rst, clk, en;
  output [7:0] c;
  wire rst, clk, en;
  wire [7:0] c;
  wire n_0, n_3, n_5, n_6, n_7, n_8, n_9, n_10;
  wire n_11, n_12, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_21, n_23, n_24, n_25, n_26, n_29, n_30, n_31;
  wire n_32, n_33, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_59, n_60;
  wire n_61, n_62, n_63, n_64;
  OAI22X2 g536(.A0 (n_45), .A1 (n_43), .B0 (n_44), .B1 (n_60), .Y
       (n_47));
  OAI22X2 g539(.A0 (n_45), .A1 (n_40), .B0 (n_44), .B1 (n_30), .Y
       (n_46));
  AOI2BB2X2 g540(.A0N (n_42), .A1N (n_41), .B0 (n_42), .B1 (n_41), .Y
       (n_43));
  ADDHX4 g542(.A (n_29), .B (n_37), .CO (n_41), .S (n_40));
  OAI22X2 g543(.A0 (n_45), .A1 (n_38), .B0 (n_44), .B1 (n_24), .Y
       (n_39));
  ADDHX4 g548(.A (n_23), .B (n_32), .CO (n_37), .S (n_38));
  OAI22X2 g549(.A0 (n_45), .A1 (n_33), .B0 (n_44), .B1 (n_19), .Y
       (n_36));
  ADDHX4 g553(.A (n_18), .B (n_25), .CO (n_32), .S (n_33));
  OAI22X2 g555(.A0 (n_45), .A1 (n_26), .B0 (n_44), .B1 (n_15), .Y
       (n_31));
  AOI2BB2X4 g544(.A0N (n_29), .A1N (n_62), .B0 (n_29), .B1 (n_62), .Y
       (n_30));
  ADDHX4 g560(.A (n_14), .B (n_16), .CO (n_25), .S (n_26));
  AOI2BB2X2 g550(.A0N (n_23), .A1N (n_63), .B0 (n_23), .B1 (n_63), .Y
       (n_24));
  OAI22X2 g561(.A0 (n_45), .A1 (n_17), .B0 (n_44), .B1 (n_10), .Y
       (n_21));
  MXI2X1 g556(.A (c[4]), .B (n_18), .S0 (n_12), .Y (n_19));
  ADDHX4 g565(.A (n_9), .B (n_7), .CO (n_16), .S (n_17));
  MXI2X1 g562(.A (c[3]), .B (n_14), .S0 (n_11), .Y (n_15));
  CLKAND2X3 g563(.A (c[3]), .B (n_11), .Y (n_12));
  MXI2X1 g566(.A (n_9), .B (c[2]), .S0 (n_6), .Y (n_10));
  ADDHX4 g568(.A (n_61), .B (n_5), .CO (n_7), .S (n_8));
  NOR2X4 g567(.A (n_9), .B (n_6), .Y (n_11));
  DFFTRX4 \c_reg[0] (.CK (clk), .D (n_5), .RN (n_0), .Q (c[0]), .QN
       (n_5));
  CLKINVX8 g570(.A (n_64), .Y (n_44));
  CLKINVX8 g573(.A (n_3), .Y (n_45));
  NOR2X8 g574(.A (en), .B (rst), .Y (n_3));
  NAND2X6 g572(.A (c[1]), .B (c[0]), .Y (n_6));
  CLKINVX16 g579(.A (rst), .Y (n_0));
  XNOR2X4 g2(.A (n_59), .B (n_42), .Y (n_60));
  NAND2BX4 g3(.AN (n_29), .B (n_62), .Y (n_59));
  DFFX4 \c_reg[7] (.CK (clk), .D (n_47), .Q (c[7]), .QN (n_42));
  DFFX4 \c_reg[2] (.CK (clk), .D (n_21), .Q (c[2]), .QN (n_9));
  SDFFX4 \c_reg[1] (.CK (clk), .D (n_3), .SE (n_8), .SI (n_64), .Q
       (c[1]), .QN (n_61));
  DFFX4 \c_reg[5] (.CK (clk), .D (n_39), .Q (c[5]), .QN (n_23));
  DFFX4 \c_reg[4] (.CK (clk), .D (n_36), .Q (c[4]), .QN (n_18));
  DFFX4 \c_reg[6] (.CK (clk), .D (n_46), .Q (c[6]), .QN (n_29));
  DFFX2 \c_reg[3] (.CK (clk), .D (n_31), .Q (c[3]), .QN (n_14));
  NOR2BX4 g607(.AN (n_63), .B (n_23), .Y (n_62));
  NOR2BX4 g608(.AN (n_12), .B (n_18), .Y (n_63));
  NOR2BX4 g609(.AN (en), .B (rst), .Y (n_64));
endmodule

